"""Regenerate WIDGET_ORDER_baseline_vNNN.txt for THIS tree.

Regenerating a baseline is a DECLARED act: it belongs in the cut that changes
the canon, and the cut's changelog must name it. This script exists so that
act is mechanical and cannot drift from the guard that checks it -- the scan
is imported FROM tests/test_v577_widget_order.py, not re-implemented here.
Re-implementing it would create a second truth, and the second truth is
always the one that is wrong.

Usage (from the pack root):

    python3 tools/make_widget_baseline.py 368

Writes WIDGET_ORDER_baseline_v368.txt. Delete the previous baseline in the
same cut -- the guard refuses to run when it finds two, on purpose.
"""
import glob
import importlib.util
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """
#
# WIDGET_ORDER baseline -- generated by tools/make_widget_baseline.py
#
# Format:  NODE_ID <TAB> widget,widget,...      DYNAMIC: built at runtime.
# LiteGraph restores widgets_values POSITIONALLY. Slip a widget into the
# middle of an INPUT_TYPES and every saved workflow silently shifts.
# Order = required widgets, then optional widgets, in declaration order.
# WIDGETS only. Link-typed inputs (IMAGE, MODEL, LATENT, '*', ...) are SOCKETS
# and never occupy a widgets_values slot, so they may be added anywhere.
#
""".lstrip("\n")


def _load_guard():
    path = os.path.join(ROOT, "tests", "test_v577_widget_order.py")
    spec = importlib.util.spec_from_file_location("_v577", path)
    mod = importlib.util.module_from_spec(spec)
    # The guard resolves its baseline at import time and exits when none is
    # present -- which is exactly the situation this script is here to fix.
    # Swallow that one exit, keep every other failure loud.
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    return mod


def main():
    if len(sys.argv) != 2 or not sys.argv[1].isdigit():
        print("usage: python3 tools/make_widget_baseline.py <version-number>")
        sys.exit(2)
    ver = sys.argv[1]
    guard = _load_guard()
    scan = guard._scan()

    # CANON lines (v770) are NOT derivable from the AST -- that is their whole
    # point: the node sorts its INPUT_TYPES at runtime, so only running it tells
    # you the order. They are therefore CARRIED FORWARD from the previous
    # baseline and left for the guard to verify against _runtime_order.
    # Dropping them silently downgrades a guarded node to an unguarded one:
    # regenerating over a v841 baseline turned ULSCutout from "checked by its
    # declared canon" into a bare DYNAMIC line, and the run still went green
    # because DYNAMIC means "not guarded". Caught by diffing old against new.
    carried = {}
    for prev in glob.glob(os.path.join(ROOT, "WIDGET_ORDER_baseline_v*.txt")):
        for line in open(prev, encoding="utf-8"):
            parts = line.rstrip("\n").split("\t")
            if parts[0] == "CANON" and len(parts) == 4:
                carried[parts[1]] = line.rstrip("\n")

    lines = [HEADER]
    for cls in sorted(scan):
        order, dynamic, _file = scan[cls]
        if cls in carried:
            lines.append(carried[cls])
            continue
        if dynamic:
            # The marker leads the line -- _load_baseline() reads column 0.
            # Writing "<node>\tDYNAMIC" instead parses as a STATIC node with a
            # single widget literally named DYNAMIC, and the guard then fails
            # with a message about an undeclared dynamic node. Caught here.
            lines.append(f"DYNAMIC\t{cls}")
        else:
            lines.append(f"{cls}\t" + ",".join(order))

    out = os.path.join(ROOT, f"WIDGET_ORDER_baseline_v{ver}.txt")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.basename(out)} -- {len(scan)} node classes")


if __name__ == "__main__":
    main()
